---

- hosts: nginx
  become: true
  vars:
   - VarMessage: "Hello World!"
  tasks:
   - name: Set authorized key
     authorized_key:
       user: nginx
       state: present
       key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
   - name: Install Nginx
     apt:
       pkg: nginx
       state: present
       update_cache: true
   - name: Install Mailutils
     apt:
       pkg: mailutils
       state: present
       update_cache: true
   - name: index.html copy
     template:
       src: index.html.j2
       dest: /var/www/html/index.html
   - name: ip_extract.sh copy
     copy:
       src: ip_extract.sh
       dest: '/tmp/ip_extract.sh'
       owner: nginx
       group: nginx
       mode: 0755
   - name: Cron for stats
     cron:
       name: Email Access Stats
       user: nginx
       minute: 0
       hour: "*/2"
       job: grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}' /var/log/nginx/access.log |sort |uniq -c |sort -rn |mail -s nginx_stats <mail_recipient>

...
