---

- hosts: nginx
  become: true
  vars:
   - VarMessage: "Hello World!"
  tasks:
   - name: Set authorized key
     authorized_key:
       user: nginx
       state: present
       key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
   - name: Nginx Install
     apt:
       pkg: nginx
       state: present
       update_cache: true
   - name: index.html copy
     template:
       src: index.html.j2
       dest: /var/www/html/index.html
   - name: ip_extract.sh copy
     copy:
       src: ip_extract.sh
       dest: ip_extract.sh
       owner: foo
       group: foo
       mode: 0755
   - name: Mail Install
     apt:
       pkg: mailutils
       state: present
       update_cache: true
   - name: Cron for stats
     cron:
       name: Email Stats
       minute: 0
       hour: "*/2"
       job: ~/ip_extract.sh |mail -s nginx_stats example@gmail.com

...
